---
# host prueba
- hosts: all
  gather_facts: true
  connection: local
# module required
  tasks:
   - name: show run 
   ios_command:
   commands:
     - show run 
     host: "{{ ansible_host }}"
# user key master
     username: username
     password: password
     register: config
# backup path
  - name: save output to /etc/ansible/backups 
  copy: 
  content: "{{ config.stdout[0] }}"
  dest: "/etc/ansible/backups/show_run_{{ inventory_hostname }}.txt"
